<a href="https://www.kaggle.com/code/valeriislynko/clswrk-pytorch?scriptVersionId=352485260" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [12]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [3]:
import torch

print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

False
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [4]:
tensor = torch.randn(2,3)

In [5]:
tensor

tensor([[ 0.1637, -1.8541, -1.3270],
        [ 0.2120,  0.5404,  0.2964]])

In [6]:
tensor.dtype

torch.float32

In [7]:
tensor.shape

torch.Size([2, 3])

In [8]:
tensor.device

device(type='cpu')

# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [21]:
# 1. Створюємо 2 тензора розміру 100
tensor1 = torch.randn(100)
tensor2 = torch.randn(100)

In [22]:
# 2. Сума векторів
tensor_sum = tensor1 + tensor2
print("Сума векторів:", tensor_sum)

Сума векторів: tensor([-1.3804,  1.8454, -3.0439, -0.0384,  1.4244,  1.3488, -0.5544, -1.5553,
         0.6621, -2.3280,  0.0744, -0.6701,  0.1217, -1.4948,  1.3962,  0.7455,
         0.6991,  1.4733,  0.1119, -3.5359, -3.2392, -0.8805,  0.5260,  0.2845,
        -0.7553, -1.9467, -1.0619, -0.8662,  0.1313, -0.1651,  0.0823,  0.0585,
         1.1192,  0.6428,  2.7959,  2.4926,  2.0658,  0.6771, -1.0669, -1.5615,
        -0.4719, -1.3017, -1.6619,  0.6022, -0.8180, -1.6103,  0.1289, -1.8030,
         0.4363,  0.6519,  0.5307, -1.5063,  0.5807, -2.3686,  0.8743, -1.3478,
        -1.1040,  0.5145,  0.4910,  1.2886, -0.2227,  0.8090,  0.9647,  1.4028,
         1.0368, -0.2976, -1.7157, -1.0241,  0.2206,  1.8302, -0.7025,  0.5701,
         0.3073,  1.2715, -0.0976,  0.3306,  0.7998, -0.7161, -0.9285, -0.9060,
         2.2441,  1.1667,  0.3245, -0.1552, -0.6510,  0.2834,  2.4480,  0.0596,
        -2.1256,  1.7734,  0.6013,  0.2767,  0.4855,  1.9567,  0.1099, -0.4739,
        -0.6506, -0.6967,

In [23]:
# 3. Частка векторів (замінюємо один елемент tensor2[0] на 0)
tensor2[0] = 0
tensor_div = tensor1 / tensor2
print("Частка векторів:", tensor_div)

Частка векторів: tensor([        inf,  1.8629e+00,  9.8482e-01, -9.6782e-01, -7.0942e-02,
         1.0447e+02, -2.7193e-01, -1.3361e-01,  1.0992e+00,  3.1580e+00,
        -1.1281e+00, -3.1672e+00, -1.1274e+00,  1.5139e+00,  3.3047e-01,
         6.4055e-01,  6.0714e-01,  3.3417e+00, -1.1472e+00,  2.4528e+00,
         1.1167e+00, -3.1404e-01, -4.4134e-02, -7.1103e-01, -5.3021e-01,
         1.9701e-02,  3.6603e-01, -4.5092e-01, -7.9234e-01, -1.1173e+00,
        -6.2897e-01, -1.0718e+00,  9.0161e+00, -4.1608e-01,  2.7627e+00,
         8.2304e-01,  2.7996e+00, -4.3374e-01,  2.0397e+01, -2.5049e+00,
        -3.2142e+00,  8.7726e-01,  1.2907e+00, -3.4256e-01, -2.2766e-01,
         3.7836e-01, -5.6428e-02,  2.2227e+00, -3.0495e+00, -3.8601e-01,
         5.2252e-01, -1.6739e-01, -3.7712e+00,  5.7688e-01,  1.9480e+00,
         4.1081e-01,  3.0838e+01,  1.0477e+00,  1.2545e+00,  1.2126e-01,
        -6.2551e-01, -5.1356e-01,  4.0852e-01, -1.5880e-01,  1.3446e+01,
        -1.3575e+00,  1.4472e+00, 

In [24]:
# 4. Максимальне та мінімальне значення
print("Мінімальне значення tensor1:", tensor1.min())
print("Максимальне значення tensor1:", tensor1.max())

Мінімальне значення tensor1: tensor(-2.5991)
Максимальне значення tensor1: tensor(2.1430)


In [25]:
# 5. Середнє значення
print("Середнє значення tensor1:", tensor1.mean())

Середнє значення tensor1: tensor(0.0221)


In [26]:
# 6. Квадрат різниці
tensor_diff = tensor1 - tensor2
tensor_squar = tensor_diff ** 2
print("Квадрат різниці:", tensor_squar)

Квадрат різниці: tensor([1.1453e-01, 3.0937e-01, 5.4179e-04, 5.5256e+00, 2.6958e+00, 1.7508e+00,
        9.3810e-01, 4.1411e+00, 9.7828e-04, 1.4598e+00, 1.5276e+00, 1.6602e+00,
        4.1282e+00, 9.3374e-02, 4.9365e-01, 2.6681e-02, 2.9206e-02, 6.3139e-01,
        2.6641e+00, 2.2135e+00, 3.1913e-02, 2.8449e+00, 3.3011e-01, 2.8380e+00,
        6.0533e+00, 3.5025e+00, 2.4285e-01, 5.2392e+00, 1.2842e+00, 8.8868e+00,
        1.3050e-01, 2.8540e+00, 8.0225e-01, 2.4300e+00, 1.7156e+00, 5.8541e-02,
        9.5730e-01, 2.9394e+00, 9.3536e-01, 1.3226e+01, 8.0664e-01, 7.2437e-03,
        4.4485e-02, 1.5122e+00, 1.6908e+00, 5.2744e-01, 2.0820e-02, 4.6793e-01,
        7.4322e-01, 2.1655e+00, 2.7703e-02, 4.4603e+00, 9.9967e-01, 4.0392e-01,
        7.9058e-02, 3.1685e-01, 1.0706e+00, 1.4351e-04, 3.0725e-03, 1.0198e+00,
        9.3430e-01, 6.3371e+00, 1.6410e-01, 3.7343e+00, 7.9798e-01, 3.8504e+00,
        9.8313e-02, 1.2163e+00, 8.1901e-01, 4.8073e+00, 4.6910e+00, 1.8978e+00,
        2.8485e-05, 2.0

In [27]:
# 7. Середнє значення квадрату різниці (MSE)
mse = tensor_squar.mean()
print("Середнє значення квадрату різниці:", mse)

Середнє значення квадрату різниці: tensor(1.7834)


# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [5]:
import torch


class NeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [8]:
# Ваш код
model = NeuralNetwork(device = 'cpu')

In [13]:
 tensor = torch.tensor([65.0, 2.0])

In [14]:
tensor_new = tensor.reshape(1, 2)

In [15]:
tensor_new.shape

torch.Size([1, 2])

In [16]:
model.predict(tensor_new)

tensor([[314.5000]], grad_fn=<AddBackward0>)

# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [17]:
model = NeuralNetwork(device = 'cpu')

In [24]:
app1 = torch.tensor([40.0,1.0])
app2 = torch.tensor([60.0,3.0])
app3 = torch.tensor([100.0,2.0])

In [25]:
app1 = app1.reshape(1, 2)
app2 = app2.reshape(1, 2)
app3 = app3.reshape(1, 2)

In [26]:
app1.shape

torch.Size([1, 2])

In [27]:
# app1 = app1.to('cpu')
# app2 = app1.to('cuda')
# app3 = app1.to('cuda')

# app1

In [28]:
model.predict(app1)

tensor([[270.]], grad_fn=<AddBackward0>)

In [29]:
model.predict(app2)

tensor([[260.]], grad_fn=<AddBackward0>)

In [30]:
model.predict(app3)

tensor([[430.]], grad_fn=<AddBackward0>)

In [32]:
X = torch.tensor([
    [40.0,1.0],
    [60.0,3.0],
    [100.0,2.0]
    ])

In [ ]:
# X = X.to('cuda')

In [33]:
model.predict(X)

tensor([[270.],
        [260.],
        [430.]], grad_fn=<AddBackward0>)

# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [54]:
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    MAE = y_pred - y_true
    MAE_new = MAE.abs()
    MAE_mean = MAE_new.mean()
    return MAE_mean
    

In [52]:
y_true = torch.tensor([210.0, 310.0, 360.0])

In [47]:
y_true = y_true.reshape(3, 1)

In [48]:
y_pred = model.predict(X)
y_pred.shape

torch.Size([3, 1])

In [55]:
loss_fn(y_pred, y_true)

tensor(88.8889, grad_fn=<MeanBackward0>)

# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [ ]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


# Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [ ]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
