<a href="https://www.kaggle.com/code/valeriislynko/hmwrk-pytorch-26-09-26?scriptVersionId=354690367" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [317]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [318]:
import torch

print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

True
2
Tesla T4
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [319]:
tensor = torch.randn(2,3)

In [320]:
tensor

tensor([[-2.0468, -0.2597, -0.0972],
        [-0.4217,  1.7851,  1.0751]])

In [321]:
tensor.dtype

torch.float32

In [322]:
tensor.shape

torch.Size([2, 3])

In [323]:
tensor.device

device(type='cpu')

# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [324]:
# 1. Створюємо 2 тензора розміру 100
tensor1 = torch.randn(100)
tensor2 = torch.randn(100)

In [325]:
# 2. Сума векторів
tensor_sum = tensor1 + tensor2
print("Сума векторів:", tensor_sum)

Сума векторів: tensor([ 0.4255,  1.1997,  0.7440,  1.0086, -0.0969, -3.3687,  1.4915, -1.7428,
        -0.1327, -0.3724, -2.0252,  0.8171,  0.8614, -0.5088,  0.8558, -1.4865,
         0.7795, -1.7042, -2.2172, -0.4941,  0.0228,  2.4921, -0.8985,  0.1366,
        -0.5860,  0.2897, -0.6729, -0.0106,  1.0893, -1.1371,  2.6930,  0.6863,
         1.2197,  0.4186,  1.0185, -0.1684,  0.1603,  1.0879,  0.5398, -0.0651,
        -4.1795,  0.0339,  0.7007, -0.1565, -1.3385,  1.0615, -0.9444,  1.2880,
        -0.6374,  1.9738,  0.4310, -1.2012,  0.5610,  1.2946, -1.8274,  1.7187,
        -0.3030,  3.4017,  0.6988, -0.4311, -0.4494,  1.4176, -0.4493, -1.7407,
        -0.8741,  0.9972, -2.4242, -0.3790, -0.4936, -0.5125, -0.8447,  2.0634,
         0.7103, -1.2187,  0.0928, -0.5663,  1.1078, -0.3596,  0.1952, -3.5144,
        -1.4015,  1.4670, -1.1921, -0.7215,  0.3924, -1.8366, -0.3646,  1.0397,
         0.6662, -0.8632,  1.3162,  0.7584,  1.6199,  1.5550,  2.1622, -2.4571,
        -1.4762, -0.2315,

In [326]:
# 3. Частка векторів (замінюємо один елемент tensor2[0] на 0)
tensor2[0] = 0
tensor_div = tensor1 / tensor2
print("Частка векторів:", tensor_div)

Частка векторів: tensor([     inf,  -0.4952,  -0.0242,   2.8506,  -0.4785,   0.7119,   2.1279,
          0.5863,  -0.7568,  -2.6852,   0.2786,   0.5271,   0.1778,  -0.5200,
         -0.2391,   0.1489,   0.6463,   2.3486,   1.3363,  -2.7001,  -0.9349,
          1.8338,  -0.4152,  -2.1704,  -0.4385,  -6.6291,  -4.5652,  -1.0091,
         -4.6686,   2.1660,   0.7929,  -0.2259,   2.2841,  -3.7804,   0.6503,
         -1.3452,  -1.2476,   0.5200, -16.4878,  -0.9051,   1.4123,  -1.1054,
          0.9089,  -2.2118,   3.1400,   0.6084,   4.0640,   0.0427,  -0.3254,
          2.7718,  -1.3878,   0.3216,  11.8797,   1.2288,   0.5246,   0.3045,
         -0.4919,   0.8916,   1.3799,   0.4751,  -2.5849,   0.3932,  -0.7246,
          0.6340,  -0.0908,   1.8392,   2.1032,   0.5557,   1.4676,   0.3233,
          0.1192,  10.0079,  -0.0281,  -3.5862,  -1.1901,  -0.6837,   1.5605,
         -1.8197,  -0.8412,   9.3578,  -0.2367,  -2.1695,  -0.1694,   0.5203,
         -0.5196,   1.0672,  -1.4635,   0.6258,

In [327]:
# 4. Максимальне та мінімальне значення
print("Мінімальне значення tensor1:", tensor1.min())
print("Максимальне значення tensor1:", tensor1.max())

Мінімальне значення tensor1: tensor(-3.1751)
Максимальне значення tensor1: tensor(2.7214)


In [328]:
# 5. Середнє значення
print("Середнє значення tensor1:", tensor1.mean())

Середнє значення tensor1: tensor(0.0404)


In [329]:
# 6. Квадрат різниці
tensor_diff = tensor1 - tensor2
tensor_squar = tensor_diff ** 2
print("Квадрат різниці:", tensor_squar)

Квадрат різниці: tensor([2.6888e-01, 1.2628e+01, 6.0977e-01, 2.3495e-01, 7.5401e-02, 3.2133e-01,
        2.8928e-01, 2.0653e-01, 9.1880e-01, 6.6336e-01, 1.3058e+00, 6.4048e-02,
        3.6155e-01, 2.5955e+00, 1.9421e+00, 1.2127e+00, 2.8036e-02, 4.7106e-01,
        1.0185e-01, 1.1564e+00, 4.5782e-01, 5.3766e-01, 4.7272e+00, 1.3693e-01,
        2.2543e+00, 1.5420e-01, 1.1033e+00, 5.4285e+00, 2.8329e+00, 1.7536e-01,
        9.6814e-02, 1.1812e+00, 2.2746e-01, 5.1804e-01, 4.6580e-02, 1.3093e+00,
        2.1175e+00, 1.1799e-01, 3.7149e-01, 1.7065e+00, 5.1031e-01, 4.5734e-01,
        1.1193e-03, 1.7199e-01, 4.7867e-01, 6.6781e-02, 3.2650e-01, 1.3982e+00,
        1.5686e+00, 8.5970e-01, 7.0424e+00, 3.8020e-01, 2.2460e-01, 1.7656e-02,
        3.2470e-01, 8.3967e-01, 7.9140e-01, 3.7985e-02, 1.2444e-02, 2.3528e-02,
        1.0335e+00, 3.8115e-01, 7.9143e+00, 1.5206e-01, 1.0998e+00, 8.6872e-02,
        7.4269e-01, 1.1716e-02, 8.7514e-03, 6.8702e-02, 4.4190e-01, 2.8512e+00,
        5.6459e-01, 4.6

In [330]:
# 7. Середнє значення квадрату різниці (MSE)
mse = tensor_squar.mean()
print("Середнє значення квадрату різниці:", mse)

Середнє значення квадрату різниці: tensor(1.5909)


# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [331]:
import torch


class NeuralNetwork:
    def __init__(self, device="cuda"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [332]:
# Ваш код
model = NeuralNetwork(device = 'cuda')

In [333]:
 tensor = torch.tensor([65.0, 2.0])

In [334]:
tensor_new = tensor.reshape(1, 2)

In [335]:
tensor_new.shape

torch.Size([1, 2])

In [336]:
tensor_new = tensor_new.to("cuda")
tensor_new

tensor([[65.,  2.]], device='cuda:0')

In [337]:
model.predict(tensor_new)

tensor([[314.5000]], device='cuda:0', grad_fn=<AddBackward0>)

# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [338]:
model = NeuralNetwork(device = 'cuda')

In [339]:
app1 = torch.tensor([40.0,1.0])
app2 = torch.tensor([60.0,3.0])
app3 = torch.tensor([100.0,2.0])

In [340]:
app1 = app1.reshape(1, 2)
app2 = app2.reshape(1, 2)
app3 = app3.reshape(1, 2)

In [341]:
app1.shape

torch.Size([1, 2])

In [342]:
app1 = app1.to('cuda')
app2 = app1.to('cuda')
app3 = app1.to('cuda')

app1

tensor([[40.,  1.]], device='cuda:0')

In [343]:
model.predict(app1)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [344]:
model.predict(app2)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [345]:
model.predict(app3)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [346]:
X = torch.tensor([
    [40.0,1.0],
    [60.0,3.0],
    [100.0,2.0]
    ])

In [347]:
X = X.to('cuda')

In [348]:
X

tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')

In [349]:
model.predict(X)

tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)

# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [350]:
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    y_true = y_true.to(y_pred.device)
    MAE = y_pred - y_true
    MAE_new = MAE.abs()
    MAE_mean = MAE_new.mean()
    return MAE_mean
    

In [351]:
y_true = torch.tensor([210.0, 310.0, 360.0])

In [352]:
y_true = y_true.reshape(3, 1)

In [353]:
y_pred = model.predict(X)
y_pred.shape

torch.Size([3, 1])

In [354]:
loss_fn(y_pred, y_true)

tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)

**<<< ДОМАШНЄ ЗАВДАННЯ (від 26.09.26р.) >>>**

# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [355]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


In [356]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Використовуємо пристрій: {device}")

Використовуємо пристрій: cuda


In [357]:
# 1. Створюємо об'єкт класу Teacher, передавши йому модель
teacher = Teacher(model, lr = 0.02)

In [358]:
teacher

In [359]:
# 2. Виводимо тензори X (дані про квартири) та y_true (реальні ціни з Завдання 7)
# Створюємо тензори одразу на відповідному device 
X = torch.tensor([
    [40.0, 1.0],
    [60.0, 3.0],
    [100.0, 2.0]
], device= device)
# показуємо/перевіряємо тензори 'X'
print("Тензор X (площа, кількість кімнат):\n", X)

Тензор X (площа, кількість кімнат):
 tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')


In [360]:
# Виводимо тензори y_true (реальні ціни)
y_true = torch.tensor([
    [210],
    [310],
    [360]
], device = device)
print("Тензор y_true (реальні ціни квартир):\n", y_true)

Тензор y_true (реальні ціни квартир):
 tensor([[210],
        [310],
        [360]], device='cuda:0')


In [361]:
# Отримуємо та виводимо початковий прогноз y_pred
y_pred = model.predict(X)
print("Початкові прогнозні ціни:\n", y_pred)

Початкові прогнозні ціни:
 tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)


In [362]:
# 4. Обчислюємо та виводимо початкову помилку за допомогою функції loss_fn()
loss = loss_fn(y_pred, y_true)
print("Початкова помилка моделі (Loss):\n", loss)

Початкова помилка моделі (Loss):
 tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)


In [363]:
# 5. Передаємо обчислену помилку в метод teach() для навчання моделі
teacher.teach(loss)

In [364]:
# 6. Отримуємо та виводимо НОВИЙ ПРОГНОЗ 'y_pred' після одного кроку навчання
y_pred_new = model.predict(X)
print("Оновлені прогнозні ціни після одного кроку 'y_pred_new':\n", y_pred_new)

Оновлені прогнозні ціни після одного кроку 'y_pred_new':
 tensor([[248.6600],
        [227.9933],
        [376.6600]], device='cuda:0', grad_fn=<AddBackward0>)


In [365]:
# 7. Отримуємо та виводимо НОВИЙ ПРОГНОЗ 'y_pred' після одного кроку навчання
loss_new = loss_fn(y_pred_new, y_true)
print("Нова помилка моделі (loss_new):\n", loss_new)

Нова помилка моделі (loss_new):
 tensor(45.7756, device='cuda:0', grad_fn=<MeanBackward0>)


In [366]:
print(f'loss_new={loss_new} < loss={loss}, це означає, що значення функції втрат (MAE) зменшилося,\n'
      'і модель після одного кроку градієнтного спуску почала прогнозувати ціни точніше '
      '(ваги та зсув скоригувалися у напрямку зменшення помилки)')

loss_new=45.775550842285156 < loss=60.0, це означає, що значення функції втрат (MAE) зменшилося,
і модель після одного кроку градієнтного спуску почала прогнозувати ціни точніше (ваги та зсув скоригувалися у напрямку зменшення помилки)


# .Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

In [367]:
# 1. Створення об'єкта класу Teacher, передавши йому модель
# (припускаємо, що клас Teacher та loss_fn вже оголошені у ноутбуці)
teacher = Teacher(model, lr=0.001)  # коригування навчального кроку (lr)
teacher

In [368]:
# 2. Створення тензора X (вхідні дані про квартири) та y_true (реальні ціни)
# Підвантажуємо X та y_true до CUDA 
X = X.to(device)
y_true = y_true.to(device)

# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [369]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
