<a href="https://www.kaggle.com/code/valeriislynko/hmwrk-pytorch-26-09-26?scriptVersionId=354718318" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

Імпорт модулів

In [195]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [196]:
import torch

print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

True
2
Tesla T4
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [197]:
tensor = torch.randn(2,3)

In [198]:
tensor

tensor([[-2.2575,  0.3381, -2.2861],
        [-0.2399,  0.1270,  0.5455]])

In [199]:
tensor.dtype

torch.float32

In [200]:
tensor.shape

torch.Size([2, 3])

In [201]:
tensor.device

device(type='cpu')

# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [202]:
# 1. Створюємо 2 тензора розміру 100
tensor1 = torch.randn(100)
tensor2 = torch.randn(100)

In [203]:
# 2. Сума векторів
tensor_sum = tensor1 + tensor2
print("Сума векторів:", tensor_sum)

Сума векторів: tensor([ 0.2015,  0.3280, -0.9897,  0.6609,  2.2258,  2.5699, -1.9104, -0.2234,
         1.0777, -0.9420,  0.2953,  0.5634, -1.5818,  0.6068, -2.0538,  1.1419,
        -2.4617,  0.1938, -2.2776,  1.1390,  0.7360, -0.8840, -1.3522,  1.3689,
        -2.1985,  0.3786, -1.2599, -0.3793,  0.5342, -0.5653, -1.8481, -0.8491,
        -0.3542, -2.5551,  1.2101,  1.2625, -1.8381,  0.0372,  0.9079,  0.6987,
        -1.6218, -1.9806,  0.5498,  0.8418, -0.9255, -1.2085, -1.5928, -2.2201,
        -2.7947,  1.1445, -0.7587,  0.3720, -0.4013,  0.0705, -0.2466, -2.2674,
         0.7805, -1.8975, -0.6691,  0.6460, -0.5968, -0.3458, -0.1319, -0.2959,
        -0.4783, -1.3816, -0.6539, -2.8967,  0.3267, -2.4214,  0.4114, -0.5886,
        -0.4037,  0.3855, -2.2428,  0.1533,  1.8336, -2.1490,  1.0589, -2.2865,
        -0.2269,  0.1774, -1.2311, -1.3533,  0.9645,  1.8712,  0.1948,  0.7675,
        -0.4451,  0.0659,  0.6227,  0.9266, -2.0321, -2.2440,  1.9403, -2.0457,
         0.2544,  0.8642,

In [204]:
# 3. Частка векторів (замінюємо один елемент tensor2[0] на 0)
tensor2[0] = 0
tensor_div = tensor1 / tensor2
print("Частка векторів:", tensor_div)

Частка векторів: tensor([        inf, -5.2886e-01, -3.8457e-01,  3.2141e+00, -2.0950e+01,
         2.4178e+00,  1.8370e-01, -3.2673e+00, -2.9660e-01,  2.0694e+00,
        -1.5566e+01, -4.2351e-01, -1.4438e+01, -2.0490e+00,  1.1583e+00,
         7.6940e-01,  1.5654e+00, -1.6136e-01,  3.1655e-01,  1.7240e+00,
        -3.4490e-02,  9.6756e+00, -3.2614e+00, -1.4940e-01,  1.8426e+00,
        -5.5011e+00,  2.9246e+00, -1.8707e+00, -2.9485e+00, -7.6661e-01,
         1.1555e+01,  4.2885e+00, -2.6461e-01,  1.1203e+00, -1.6006e+01,
         4.0424e+00,  1.2151e+00, -9.7512e-01, -1.1779e+01, -3.0515e+00,
         1.1260e-02,  2.2467e+00,  1.1504e+00,  2.4598e-02,  1.5798e+00,
         3.5335e+00, -8.2770e-02, -2.8062e-01,  1.1327e-01, -2.9095e+00,
         8.4102e+00,  1.8578e-01, -1.8595e-01, -9.2901e-01, -1.2630e+00,
         1.2037e+00,  1.6166e+00, -3.3978e-02,  1.9971e-01, -3.3623e+00,
        -2.3500e-01, -6.7382e-01, -1.3714e+00, -1.1666e+00, -1.5343e-01,
         4.1662e-01, -4.1202e+00, 

In [205]:
# 4. Максимальне та мінімальне значення
print("Мінімальне значення tensor1:", tensor1.min())
print("Максимальне значення tensor1:", tensor1.max())

Мінімальне значення tensor1: tensor(-2.1538)
Максимальне значення tensor1: tensor(2.3373)


In [206]:
# 5. Середнє значення
print("Середнє значення tensor1:", tensor1.mean())

Середнє значення tensor1: tensor(-0.0997)


In [207]:
# 6. Квадрат різниці
tensor_diff = tensor1 - tensor2
tensor_squar = tensor_diff ** 2
print("Квадрат різниці:", tensor_squar)

Квадрат різниці: tensor([3.7802e-02, 1.1327e+00, 4.9576e+00, 1.2058e-01, 5.9970e+00, 1.1366e+00,
        1.7357e+00, 1.7687e-01, 3.9468e+00, 1.0773e-01, 1.1281e-01, 1.9354e+00,
        3.3025e+00, 3.1109e+00, 2.2701e-02, 2.2147e-02, 2.9439e-01, 7.2014e-02,
        1.3980e+00, 9.1649e-02, 6.2187e-01, 5.1611e-01, 6.4929e+00, 3.4217e+00,
        4.2469e-01, 2.9910e-01, 3.8173e-01, 1.5637e+00, 1.1716e+00, 1.8309e+01,
        2.4140e+00, 2.7879e-01, 3.7106e-01, 2.1021e-02, 1.8807e+00, 5.8029e-01,
        3.1858e-02, 8.7421e+00, 1.1585e+00, 1.9041e+00, 2.5143e+00, 5.7840e-01,
        1.4782e-03, 6.4225e-01, 4.3265e-02, 4.5609e-01, 3.5352e+00, 1.5619e+01,
        4.9550e+00, 5.4903e+00, 3.5691e-01, 6.5236e-02, 3.4179e-01, 3.6725e+00,
        4.5013e+00, 4.3922e-02, 3.3831e-02, 4.1248e+00, 1.9920e-01, 1.4229e+00,
        9.2817e-01, 3.1488e+00, 7.0903e-01, 1.4806e+01, 4.2469e-01, 3.2373e-01,
        1.1515e+00, 1.6214e+00, 7.0096e-01, 3.6401e-01, 3.4247e-01, 1.6521e+00,
        9.9045e+00, 8.1

In [208]:
# 7. Середнє значення квадрату різниці (MSE)
mse = tensor_squar.mean()
print("Середнє значення квадрату різниці:", mse)

Середнє значення квадрату різниці: tensor(2.6014)


# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [209]:
import torch


class NeuralNetwork:
    def __init__(self, device="cuda"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [210]:
# Ваш код
model = NeuralNetwork(device = 'cuda')

In [211]:
 tensor = torch.tensor([65.0, 2.0])

In [212]:
tensor_new = tensor.reshape(1, 2)

In [213]:
tensor_new.shape

torch.Size([1, 2])

In [214]:
tensor_new = tensor_new.to("cuda")
tensor_new

tensor([[65.,  2.]], device='cuda:0')

In [215]:
model.predict(tensor_new)

tensor([[314.5000]], device='cuda:0', grad_fn=<AddBackward0>)

# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [216]:
model = NeuralNetwork(device = 'cuda')

In [217]:
app1 = torch.tensor([40.0,1.0])
app2 = torch.tensor([60.0,3.0])
app3 = torch.tensor([100.0,2.0])

In [218]:
app1 = app1.reshape(1, 2)
app2 = app2.reshape(1, 2)
app3 = app3.reshape(1, 2)

In [219]:
app1.shape

torch.Size([1, 2])

In [220]:
app1 = app1.to('cuda')
app2 = app1.to('cuda')
app3 = app1.to('cuda')

app1

tensor([[40.,  1.]], device='cuda:0')

In [221]:
model.predict(app1)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [222]:
model.predict(app2)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [223]:
model.predict(app3)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [224]:
X = torch.tensor([
    [40.0,1.0],
    [60.0,3.0],
    [100.0,2.0]
    ])

In [225]:
X = X.to('cuda')

In [226]:
X

tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')

In [227]:
model.predict(X)

tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)

# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [228]:
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    y_true = y_true.to(y_pred.device)
    MAE = y_pred - y_true
    MAE_new = MAE.abs()
    MAE_mean = MAE_new.mean()
    return MAE_mean
    

In [229]:
y_true = torch.tensor([210.0, 310.0, 360.0])

In [230]:
y_true = y_true.reshape(3, 1)

In [231]:
y_pred = model.predict(X)
y_pred.shape

torch.Size([3, 1])

In [232]:
loss_fn(y_pred, y_true)

tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)

**<<< ДОМАШНЄ ЗАВДАННЯ (від 26.09.26р.) >>>**

# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [233]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


In [234]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Використовуємо пристрій: {device}")

Використовуємо пристрій: cuda


In [235]:
# 1. Створюємо об'єкт класу Teacher, передавши йому модель
teacher = Teacher(model, lr = 0.02)

In [236]:
teacher

In [237]:
# 2. Виводимо тензори X (дані про квартири) та y_true (реальні ціни з Завдання 7)
# Створюємо тензори одразу на відповідному device 
X = torch.tensor([
    [40.0, 1.0],
    [60.0, 3.0],
    [100.0, 2.0]
], device= device)
# показуємо/перевіряємо тензори 'X'
print("Тензор X (площа, кількість кімнат):\n", X)

Тензор X (площа, кількість кімнат):
 tensor([[ 40.,   1.],
        [ 60.,   3.],
        [100.,   2.]], device='cuda:0')


In [238]:
# Виводимо тензори y_true (реальні ціни)
y_true = torch.tensor([
    [210],
    [310],
    [360]
], device = device)
print("Тензор y_true (реальні ціни квартир):\n", y_true)

Тензор y_true (реальні ціни квартир):
 tensor([[210],
        [310],
        [360]], device='cuda:0')


In [239]:
# Отримуємо та виводимо початковий прогноз y_pred
y_pred = model.predict(X)
print("Початкові прогнозні ціни:\n", y_pred)

Початкові прогнозні ціни:
 tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)


In [240]:
# 4. Обчислюємо та виводимо початкову помилку за допомогою функції loss_fn()
loss = loss_fn(y_pred, y_true)
print("Початкова помилка моделі (Loss):\n", loss)

Початкова помилка моделі (Loss):
 tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)


In [241]:
# 5. Передаємо обчислену помилку в метод teach() для навчання моделі
teacher.teach(loss)

In [242]:
# 6. Отримуємо та виводимо НОВИЙ ПРОГНОЗ 'y_pred' після одного кроку навчання
y_pred_new = model.predict(X)
print("Оновлені прогнозні ціни після одного кроку 'y_pred_new':\n", y_pred_new)

Оновлені прогнозні ціни після одного кроку 'y_pred_new':
 tensor([[248.6600],
        [227.9933],
        [376.6600]], device='cuda:0', grad_fn=<AddBackward0>)


In [243]:
# 7. Отримуємо та виводимо НОВИЙ ПРОГНОЗ 'y_pred' після одного кроку навчання
loss_new = loss_fn(y_pred_new, y_true)
print("Нова помилка моделі (loss_new):\n", loss_new)

Нова помилка моделі (loss_new):
 tensor(45.7756, device='cuda:0', grad_fn=<MeanBackward0>)


In [244]:
print(f'loss_new={loss_new} < loss={loss}, це означає, що значення функції втрат (MAE) зменшилося,\n'
      'і модель після одного кроку градієнтного спуску почала прогнозувати ціни точніше '
      '(ваги та зсув скоригувалися у напрямку зменшення помилки)')

loss_new=45.775550842285156 < loss=60.0, це означає, що значення функції втрат (MAE) зменшилося,
і модель після одного кроку градієнтного спуску почала прогнозувати ціни точніше (ваги та зсув скоригувалися у напрямку зменшення помилки)


# .Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

In [245]:
# 1. Створення об'єкта класу Teacher, передавши йому модель
# (припускаємо, що клас Teacher та loss_fn вже оголошені у ноутбуці)
teacher = Teacher(model, lr=0.000001)  # коригування навчального кроку (lr)
teacher

In [246]:
# 2. Створення тензора X (вхідні дані про квартири) та y_true (реальні ціни)
# Підвантажуємо X та y_true до device (cuda) 
X = X.to(device)
y_true = y_true.to(device)


In [247]:
# 3. Створюємо цикл на виконання 100 разів.
for i in range(1, 100):
    # Крок 1: Модель робить новий прогноз цін
    y_pred = model.predict(X)

    # Крок 2: Рахуємо, нскільки модель помилилася
    loss = loss_fn(y_pred, y_true)

    # Крок 3: Виводимо помилку на екран (кожні 10 кроків, щоб не було 100 однакових рядків)
    if i % 10 == 0 or i ==1:
        print(f"Крок {i}: поточна помилка = {loss.item():.4f}")

    # Крок Г: Даємо вказівку вчителю скоригувати ваги моделі
    teacher.teach(loss)

# Отримуємо фінальний прогноз та виводимо порівняння
y_pred_final = model.predict(X)
loss_final = loss_fn(y_pred_final, y_true).item()

print("\nРеальні ціни:", y_true.squeeze())
print("Прогноз після 100 кроків:", y_pred_final.squeeze())
print(f"Фінальна помилка: {loss_final:.4f}")

Крок 1: поточна помилка = 45.7756
Крок 10: поточна помилка = 45.7691
Крок 20: поточна помилка = 45.7620
Крок 30: поточна помилка = 45.7549
Крок 40: поточна помилка = 45.7478
Крок 50: поточна помилка = 45.7407
Крок 60: поточна помилка = 45.7335
Крок 70: поточна помилка = 45.7264
Крок 80: поточна помилка = 45.7193
Крок 90: поточна помилка = 45.7122

Реальні ціни: tensor([210, 310, 360], device='cuda:0')
Прогноз після 100 кроків: tensor([248.5542, 227.8347, 376.3956], device='cuda:0',
       grad_fn=<SqueezeBackward0>)
Фінальна помилка: 45.7051


In [248]:
print('ВИСНОВОК ПІСЛЯ ПРОЙДЕНОГО НАВЧАННЯ МОДЕЛІ в 100 р.')
print('Після виконання 100 ітерацій циклу навчання помилка моделі (loss) зменшилася.\n'
      'Порівнюючи реальні ціни y_true з прогнозом y_pred, видно, що модель скоригувала ваги і її прогнози стали суттєво точнішими.\n'
      'Зменшення параметра lr дозволяє зробити процес навчання більш стабільним.')

ВИСНОВОК ПІСЛЯ ПРОЙДЕНОГО НАВЧАННЯ МОДЕЛІ в 100 р.
Після виконання 100 ітерацій циклу навчання помилка моделі (loss) зменшилася.
Порівнюючи реальні ціни y_true з прогнозом y_pred, видно, що модель скоригувала ваги і її прогнози стали суттєво точнішими.
Зменшення параметра lr дозволяє зробити процес навчання більш стабільним.


Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [249]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
