Імпорт модулів

In [151]:
import torch

# Завдання 1

Перегляньте інформацію про доступні процесори, та виведіть про них інформацію

In [152]:
import torch

print(torch.cuda.is_available())  # True/False

if torch.cuda.is_available():
    print(torch.cuda.device_count())  # Кількість GPU
    print(torch.cuda.get_device_name(0))  # Назва першого GPU

tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # CPU

True
2
Tesla T4
cpu


# Завдання 2
Підключіться до процесора GPU, та знову виведіть інформацію про доступні процесори

# Завдання 3
Створіть випадковий тензор розміру (2, 3). Виведіть інформацію про його:

* розмір
* тип даних
* процесор
* наявність градієнта

In [153]:
tensor = torch.randn(2,3)

In [154]:
tensor

tensor([[-0.2186, -1.0961,  1.3726],
        [ 1.3910,  1.0018,  2.0846]])

In [155]:
tensor.dtype

torch.float32

In [156]:
tensor.shape

torch.Size([2, 3])

In [157]:
tensor.device

device(type='cpu')

# Завдання 4

Створіть 2 тензора розміру 100. Виведіть
* суму векторів
* частку векторів(перед цим замініть один елемент на 0)
* максимальне та мінімальне значення(методи .min() .max())
* середнє значення(метод .mean())
* квадрад різниці
* середнє значення квадрату різниці

In [158]:
# 1. Створюємо 2 тензора розміру 100
tensor1 = torch.randn(100)
tensor2 = torch.randn(100)

In [159]:
# 2. Сума векторів
tensor_sum = tensor1 + tensor2
print("Сума векторів:", tensor_sum)

Сума векторів: tensor([ 1.6469,  0.7908,  0.3121,  1.8152,  2.6400,  1.5704, -4.4802, -1.1714,
         0.0587,  1.3690,  0.1381,  0.6352,  0.4643,  1.9140,  1.1273, -2.0634,
        -1.2584,  2.5211, -0.3953,  2.4660,  2.5089, -0.1022,  0.3491,  0.5617,
        -1.3487, -0.4568,  1.7453,  1.9016, -0.6373, -0.8594, -0.8085,  0.0684,
        -0.0416, -1.2806, -1.4379, -0.4787, -1.4213, -1.3918, -0.8567, -2.1430,
         1.8301, -1.2350,  1.1466,  1.3555,  0.6958,  2.2867, -0.7969,  1.2932,
         0.4106,  0.3220, -1.3405,  0.0520,  0.9189, -0.6918, -0.4094,  0.4272,
        -0.3934, -1.9035, -0.1989,  3.0732, -1.5265,  1.5458,  2.7840,  2.4331,
         1.9717,  0.5492,  0.4568,  0.4828, -2.2698,  2.0748, -0.5631,  0.8656,
         2.0545,  1.8337,  1.9029, -1.2130,  2.0838,  0.9800,  2.1364, -1.3786,
        -1.5269,  0.9993, -0.9349,  2.3602,  2.7711, -2.4204,  0.7182, -2.8763,
        -0.6365,  0.7481,  1.8352,  0.6054,  0.1711,  2.1029,  0.8863, -2.8745,
        -1.9185, -0.6647,

In [160]:
# 3. Частка векторів (замінюємо один елемент tensor2[0] на 0)
tensor2[0] = 0
tensor_div = tensor1 / tensor2
print("Частка векторів:", tensor_div)

Частка векторів: tensor([        inf, -1.0899e-01,  2.4171e-01,  5.7535e-01,  8.4078e-01,
         1.8015e+00,  1.2804e+00,  1.7417e+00, -1.1347e+00,  5.3123e-01,
        -7.8282e-01, -4.7846e+00, -1.5739e+00,  1.2689e+00, -5.0477e+00,
         5.1799e-01,  1.1395e-01,  1.3117e+00, -1.5080e-01,  1.1546e+00,
         8.5951e-01, -8.3692e-01,  1.2990e+00, -4.4780e-01,  1.6972e+00,
         3.0514e+00,  4.6822e-01,  1.5285e+00, -1.8204e+00,  1.8024e+00,
        -3.3441e+00, -1.0525e+00, -8.5227e-01, -5.2948e-01, -3.6401e-01,
        -1.8764e+00,  1.9014e+00,  1.4325e+01,  2.2890e+00,  4.6153e+01,
         1.5942e+00, -4.3620e+00,  1.0219e+01,  6.9593e-02, -7.5346e+00,
        -3.9390e-02,  7.0730e-01, -6.6696e-02, -2.6583e+00, -5.9249e-01,
        -5.7547e+00, -5.4502e-01,  3.1937e-01,  1.1659e+00, -1.5925e+00,
        -2.8225e+00,  8.0205e-01,  2.1842e+00,  1.8696e+00,  3.5677e+00,
        -9.7853e-02, -3.8616e+00,  5.6333e-01,  1.9636e+00, -2.8102e-02,
         2.8680e+00,  1.7628e+00, 

In [161]:
# 4. Максимальне та мінімальне значення
print("Мінімальне значення tensor1:", tensor1.min())
print("Максимальне значення tensor1:", tensor1.max())

Мінімальне значення tensor1: tensor(-2.5155)
Максимальне значення tensor1: tensor(2.4004)


In [162]:
# 5. Середнє значення
print("Середнє значення tensor1:", tensor1.mean())

Середнє значення tensor1: tensor(0.2023)


In [163]:
# 6. Квадрат різниці
tensor_diff = tensor1 - tensor2
tensor_squar = tensor_diff ** 2
print("Квадрат різниці:", tensor_squar)

Квадрат різниці: tensor([3.3639e-01, 9.6870e-01, 3.6329e-02, 2.3943e-01, 5.2147e-02, 2.0185e-01,
        3.0347e-01, 1.0042e-01, 8.6472e-01, 1.7565e-01, 1.2853e+00, 9.4263e-01,
        4.3357e+00, 5.1466e-02, 2.8371e+00, 4.2925e-01, 1.0018e+00, 1.1555e-01,
        2.8691e-01, 3.1325e-02, 3.5929e-02, 1.3247e+00, 2.0618e-03, 2.1688e+00,
        1.2154e-01, 5.3495e-02, 3.9959e-01, 1.5799e-01, 4.8005e+00, 6.0548e-02,
        2.2449e+00, 7.1320e+00, 2.7269e-01, 1.7329e+01, 9.5102e+00, 2.4680e+00,
        1.9498e-01, 1.4646e+00, 1.1274e-01, 4.2111e+00, 1.7573e-01, 3.8797e+00,
        8.8776e-01, 1.3903e+00, 8.2580e-01, 6.1218e+00, 1.8667e-02, 2.1846e+00,
        8.2068e-01, 1.5833e+00, 3.6267e+00, 3.1164e-02, 2.2469e-01, 2.8066e-03,
        3.2083e+00, 8.0275e-01, 1.8674e-03, 5.0112e-01, 3.6330e-03, 2.9846e+00,
        3.4509e+00, 6.8964e+00, 6.0470e-01, 6.2587e-01, 4.3503e+00, 7.0353e-02,
        1.5908e-02, 7.9021e-01, 3.0192e+00, 2.6707e+00, 1.2892e+00, 1.2892e+00,
        3.8891e+00, 1.1

In [164]:
# 7. Середнє значення квадрату різниці (MSE)
mse = tensor_squar.mean()
print("Середнє значення квадрату різниці:", mse)

Середнє значення квадрату різниці: tensor(1.8149)


# Завдання 5

У вашому розпорядженні є нейронна мережа, яка прогнозує **орієнтовну ціну квартири** на основі двох **ознак**:

* **площі квартири** (у квадратних метрах);
* **кількості кімнат**.

Вам надано готовий клас `NeuralNetwork` із методом `predict`.

1. Створіть екземпляр класу `NeuralNetwork`, передайте як параметр `device`.
2. За допомогою методу `predict()` визначте прогнозовану ціну квартири, яка:
   * має площу **65 м²**;
   * має **2 кімнати**.
     
3. Для цього створіть тензор із відповідними числами та скористайтесь методом `predict()`.
4. Усі нейромережі очікують дані розміру `(N, K)`, де:
   * `N` — кількість об'єктів, для яких виконується прогноз;
   * `K` — кількість ознак. У цьому випадку їх дві — **площа квартири та кількість кімнат**.

5. Спробуйте скористатись методом `predict()` разом із `torch.no_grad()`:

```python
with torch.no_grad():
    price = model.predict(...)
```

**Завдання:** отримайте прогнозовану ціну квартири та виведіть результат на екран.


In [165]:
import torch


class NeuralNetwork:
    def __init__(self, device="cuda"):
        self.device = device

        self.W = torch.tensor(
            [[3.3, -38.]],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [176.],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 2:
            raise ValueError(
                f"Очікується 2 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою (float32 або float64)."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        return X @ self.W.T + self.b


In [166]:
# Ваш код
model = NeuralNetwork(device = 'cuda')

In [167]:
 tensor = torch.tensor([65.0, 2.0])

In [168]:
tensor_new = tensor.reshape(1, 2)

In [169]:
tensor_new.shape

torch.Size([1, 2])

In [170]:
tensor_new = tensor_new.to("cuda")

In [171]:
model.predict(tensor_new)

tensor([[314.5000]], device='cuda:0', grad_fn=<AddBackward0>)

# **Завдання 6**

У таблиці наведено інформацію про три квартири.

| **Квартира** | **Площа (м²)** | **Кількість кімнат** |
| ------------ | -------------: | -------------------: |
| Квартира 1   |             40 |                    1 |
| Квартира 2   |             60 |                    3 |
| Квартира 3   |             100 |                    2 |

Виконайте наступні кроки:

1. Створіть **три окремі тензори** (`X1`, `X2`, `X3`), кожен з яких містить дані про одну квартиру.
2. За допомогою методу `predict()` обчисліть **прогнозовану ціну** для кожної квартири окремо.
3. Створіть **один тензор** `X` розміру **(3, 2)**, де:
   * кожен рядок відповідає одній квартирі;
   * перший стовпець — площа квартири;
   * другий стовпець — кількість кімнат.

4. За допомогою одного виклику `predict(X)` отримайте **прогнозовану ціну одразу для всіх трьох квартир**.
5. Виведіть розмір тензору з трьома прогнозованими цінами, який ви отримали на кроці 4.
6. Порівняйте результати, отримані окремими викликами `predict()` та одним спільним викликом `predict(X)`.


In [172]:
model = NeuralNetwork(device = 'cuda')

In [173]:
app1 = torch.tensor([40.0,1.0])
app2 = torch.tensor([60.0,3.0])
app3 = torch.tensor([100.0,2.0])

In [174]:
app1 = app1.reshape(1, 2)
app2 = app2.reshape(1, 2)
app3 = app3.reshape(1, 2)

In [175]:
app1.shape

torch.Size([1, 2])

In [176]:
app1 = app1.to('cuda')
app2 = app1.to('cuda')
app3 = app1.to('cuda')

app1

tensor([[40.,  1.]], device='cuda:0')

In [177]:
model.predict(app1)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [178]:
model.predict(app2)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [179]:
model.predict(app3)

tensor([[270.]], device='cuda:0', grad_fn=<AddBackward0>)

In [180]:
X = torch.tensor([
    [40.0,1.0],
    [60.0,3.0],
    [100.0,2.0]
    ])

In [181]:
X = X.to('cuda')

In [182]:
model.predict(X)

tensor([[270.],
        [260.],
        [430.]], device='cuda:0', grad_fn=<AddBackward0>)

# Завдання 7

Три квартири були продані, і стали відомі їхні **реальні ціни**.

| Квартира   | Реальна ціна (1000$) |
| ---------- | ---------------: |
| Квартира 1 |           210 |
| Квартира 2 |          310 |
| Квартира 3 |          360 |

Нехай прогноз моделі збережений у змінній `y_pred`, а реальні значення — у `y_true`.

Визначте, **наскільки модель помилилася**, використавши два різних підходи.

### Варіант 1

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Обчисліть середнє значення цієї різниці за допомогою `torch.mean()`.

### Варіант 2

1. Знайдіть різницю між прогнозованою та реальною ціною (`y_pred - y_true`).
2. Позбудьтеся від'ємних значень за допомогою `torch.abs()`.
3. Обчисліть середнє значення отриманих помилок.

### Запитання

1. Який із двох варіантів краще характеризує якість моделі? Поясніть свою відповідь.
2. Напишіть функцію `loss_fn()`, яка реалізує обраний варіант.

```python
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    ...
```




In [183]:
def loss_fn(y_pred, y_true):
    """
    Обчислює середню абсолютну помилку (Mean Absolute Error, MAE).

    Параметри:
        y_pred (torch.Tensor): прогнозовані значення моделі.
        y_true (torch.Tensor): реальні (правильні) значення.

    Повертає:
        torch.Tensor: середню абсолютну помилку.
    """
    y_true = y_true.to(y_pred.device)
    MAE = y_pred - y_true
    MAE_new = MAE.abs()
    MAE_mean = MAE_new.mean()
    return MAE_mean
    

In [184]:
y_true = torch.tensor([210.0, 310.0, 360.0])

In [185]:
y_true = y_true.reshape(3, 1)

In [186]:
y_pred = model.predict(X)
y_pred.shape

torch.Size([3, 1])

In [187]:
loss_fn(y_pred, y_true)

tensor(60., device='cuda:0', grad_fn=<MeanBackward0>)

# Завдання 8

У вашому розпорядженні є вчитель, який може навчити нейронну мережу робити точніші прогнози **цін на квартири**.

Клас `Teacher` вже реалізований. Під час створення об'єкта необхідно передати модель, яку потрібно навчати:

```python
teacher = Teacher(model)
```

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Виведіть тензор `X`, який містить дані про квартири:
   * площу квартири;
   * кількість кімнат.

3. Виведіть тензор `y_true` з **реальними цінами квартир**.
4. Отримайте прогноз моделі `y_pred`.
5. Виведіть прогнозовані ціни квартир.
6. За допомогою власної функції `loss_fn()` обчисліть помилку моделі.
7. Виведіть значення помилки.
8. Скористайтеся методом `teach()` класу `Teacher`, передавши йому обчислену помилку.
9. Після навчання знову отримайте прогноз `y_pred`.
10. Виведіть нові прогнозовані ціни квартир.
11. Знову обчисліть та виведіть помилку.
12. Зробіть висновок: **чи стала модель прогнозувати ціни квартир точніше після одного кроку навчання?**



In [188]:
import torch


class Teacher:
    def __init__(self, model, lr=0.02):
        """
        Створює вчителя для навчання моделі.

        Параметри:
            model (NeuralNetwork): модель, яку потрібно навчати.
            lr (float): швидкість навчання.
        """
        self.model = model

        self.optimizer = torch.optim.SGD(
            [model.W, model.b],
            lr=lr
        )

    def teach(self, loss):
        """
        Виконує один крок навчання.

        Параметри:
            loss (torch.Tensor): значення функції втрат.
        """
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()


# Завдання 9

Одного кроку навчання недостатньо, щоб модель навчилася добре прогнозувати ціни. Тому повторіть процес навчання **100 разів**.

### Завдання

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить дані про квартири.
3. Створіть тензор `y_true`, який містить реальні реальні ціни.
4. Створіть цикл, який виконається **100 разів**.
5. На кожній ітерації циклу:
   * отримайте прогноз моделі `y_pred`;
   * обчисліть помилку за допомогою функції `loss_fn()`;
   * виведіть помилку на екран;
   * передайте помилку в метод `teacher.teach()`, щоб виконати один крок навчання.
    
6. Після завершення циклу ще раз отримайте прогноз моделі.
7. Виведіть:
   * прогнозовані заробітні плати;
   * значення функції втрат.
    
8. Порівняйте отримані прогнози з реальними ціни. Зробіть висновок, чи покращилася точність моделі після 100 кроків навчання.
9. Cпробуйте зменшити навчальний крок в `teacher`

# Завдання 10

У вашому розпорядженні є нейронна мережа, яка прогнозує **ймовірність дощу**.

Модель використовує три ознаки:

* температура повітря (°C);
* вологість повітря (%);
* швидкість вітру (км/год).

Результатом роботи моделі є **два числа**:

1. ймовірність того, що **дощу не буде**;
2. ймовірність того, що **дощ буде**.

Скористайтеся методом `predict()`, щоб визначити ймовірності для таких погодних умов:

* температура — **20°C**;
* вологість — **80%**;
* швидкість вітру — **15 км/год**.



In [189]:
import torch


class RainNeuralNetwork:
    def __init__(self, device="cpu"):
        self.device = device

        self.W = torch.tensor(
            [
                [0.03, 0.01, 0.02],
                [0.06, -0.01, 0.08]
            ],
            requires_grad=True,
            device=device
        )

        self.b = torch.tensor(
            [-0.2, -0.3],
            requires_grad=True,
            device=device
        )

    def predict(self, X):
        if not isinstance(X, torch.Tensor):
            raise TypeError("X повинен бути об'єктом torch.Tensor.")

        if X.ndim != 2:
            raise ValueError(
                f"Очікується двовимірний тензор, отримано {X.shape}."
            )

        if X.shape[1] != 3:
            raise ValueError(
                f"Очікується 3 ознаки, отримано {X.shape[1]}."
            )

        if not X.is_floating_point():
            raise TypeError(
                "Тензор повинен містити числа з плаваючою комою."
            )

        if X.device != self.W.device:
            raise RuntimeError(
                f"X знаходиться на {X.device}, а модель на {self.W.device}."
            )

        logits = X @ self.W.T + self.b
        return torch.softmax(logits, dim=1)

# Завдання 11

Метеостанція надала прогноз погоди на **4 дні**.

| День | Температура (°C) | Вологість (%) | Швидкість вітру (км/год) |
| ---- | ---------------: | ------------: | -----------------------: |
| 1    |               30 |            40 |                        5 |
| 2    |               22 |            85 |                       18 |
| 3    |               15 |            95 |                       25 |
| 4    |               28 |            60 |                       10 |

Виконайте наступні кроки:

1. Створіть один тензор `X` розміру **(4, 3)**, де кожен рядок містить дані про один день.

2. За допомогою методу `predict()` отримайте ймовірності для кожного дня `y_pred`.

3. Скористайтеся функцією `torch.argmax(..., dim=1)`, щоб визначити прогноз моделі `result`:

   * `0` — дощу не буде;
   * `1` — дощ буде.

4. Виведіть:

   * тензор із ймовірностями `y_pred`;
   * тензор із прогнозами `result`


# Завдання 12

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
| ---- | :-: |
| 1    |  Ні |
| 2    | Так |
| 3    | Так |
| 4    |  Ні |

Для навчання моделі використайте готову функцію втрат **CrossEntropyLoss** з бібліотеки **PyTorch**.

### Завдання

1. Створіть об'єкт функції втрат:

   ```python
   loss_fn = torch.nn.CrossEntropyLoss()
   ```

2. Створіть об'єкт класу `Teacher`, передавши йому модель.

3. Створіть тензор `X`, який містить погодні умови за всі 4 дні.

4. Створіть тензор `y_true`, який містить правильні відповіді:

   * `0` — дощу не було;
   * `1` — дощ був.

5. Створіть цикл, який виконається **100 разів**.

6. На кожній ітерації циклу:

   * отримайте ймовірності від моделі `y_pred`:
   * обчисліть помилку:
   * виведіть помилку
   * передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

7. Після завершення циклу ще раз отримайте прогноз моделі.

8. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:

   * `0` — дощу не буде;
   * `1` — дощ буде.

9. Виведіть:

   * ймовірності, отримані від моделі;
   * прогнози моделі (`0` або `1`);
   * правильні відповіді
   * значення функції втра


# Завдання 13

Попробуйте натренувати модель використовуючи функцію втрат, яку ви раніше застосовували для задачі визначення цін на квартири (`torch.nn.MSELoss()`), замість `CrossEntropyLoss`.

Метеорологи повідомили, чи справді пішов дощ у кожен із чотирьох днів.

| День | Дощ |
|------|-----|
| 1    | Ні  |
| 2    | Так |
| 3    | Так |
| 4    | Ні  |

**Завдання**

1. Створіть об'єкт класу `Teacher`, передавши йому модель.
2. Створіть тензор `X`, який містить погодні умови за всі 4 дні.
3. Створіть тензор `y_true` розміром (4, 2), де кожен рядок містить інформацію про те чи йшов дощ в цей день:
   - `[1, 0]` — дощу не було
   - `[0, 1]` — дощ був
   -  формат інший тому що ваша функція вимагає щоб `y_true` та `y_pred` були однакового розміру
4. Створіть цикл, який виконається 100 разів.

На кожній ітерації циклу:
- отримайте ймовірності від моделі `y_pred`;
- обчисліть помилку;
- виведіть помилку;
- передайте помилку методу `teacher.teach(loss)` для виконання одного кроку навчання.

6. Після завершення циклу ще раз отримайте прогноз моделі.
7. За допомогою функції `torch.argmax(..., dim=1)` отримайте прогноз моделі:
   - 0 — дощу не буде;
   - 1 — дощ буде.

**Виведіть:**
- ймовірності, отримані від моделі;
- прогнози моделі (0 або 1);
- правильні відповіді;
- значення функції втрат.
